name: Update Nuget Packages

env:
  targetDirectory: Runtime/Nuget
  framework: netstandard2.0

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  install-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Check for updates Nuget Packages
        id: check
        run: |
          PuppeteerSharp_latest_version=$(nuget list PuppeteerSharp -Source "https://api.nuget.org/v3/index.json" | grep 'PuppeteerSharp' | awk '{print $2}' | sort -V | tail -n 1)
          PuppeteerSharp_current_version=$(find "${{ env.targetDirectory }}" -type d -name "PuppeteerSharp*" | grep -oP '(?<=PuppeteerSharp\.)\d+(\.\d+)*' | sort -V | tail -n 1)
          if [ -z "$PuppeteerSharp_current_version" ]; then
            PuppeteerSharp_current_version="0.0.0"
          fi
          echo "PuppeteerSharp_latest_version=$PuppeteerSharp_latest_version" >> $GITHUB_ENV
          echo "PuppeteerSharp_current_version=$PuppeteerSharp_current_version" >> $GITHUB_ENV

          SevenZipSharp_latest_version=$(nuget list Squid-Box.SevenZipSharp -Source "https://api.nuget.org/v3/index.json" | grep 'Squid-Box.SevenZipSharp' | awk '{print $2}' | sort -V | tail -n 1)
          SevenZipSharp_current_version=$(find "${{ env.targetDirectory }}" -type d -name "Squid-Box\.SevenZipSharp*" | grep -oP '(?<=Squid-Box\.SevenZipSharp\.)\d+(\.\d+)*' | sort -V | tail -n 1)
          if [ -z "$SevenZipSharp_current_version" ]; then
            SevenZipSharp_current_version="0.0.0"
          fi
          echo "SevenZipSharp_latest_version=$SevenZipSharp_latest_version" >> $GITHUB_ENV
          echo "SevenZipSharp_current_version=$SevenZipSharp_current_version" >> $GITHUB_ENV

          if [ "$PuppeteerSharp_latest_version" != "$PuppeteerSharp_current_version" ] || [ "$SevenZipSharp_latest_version" != "$SevenZipSharp_current_version" ]; then
            echo "::set-output name=update_needed::true"
          else
            echo "::set-output name=update_needed::false"
          fi
        shell: bash

      - name: Delete old Nuget Packages Directory
        if: steps.check.outputs.update_needed == 'true'
        run: rm -rf "${{ env.targetDirectory }}"
        shell: bash

      - name: Install PuppeteerSharp@latest
        if: steps.check.outputs.update_needed == 'true'
        run: nuget install PuppeteerSharp -OutputDirectory "${{ env.targetDirectory }}"
        shell: bash

      - name: Install Squid-Box.SevenZipSharp@latest
        if: steps.check.outputs.update_needed == 'true'
        run: nuget install Squid-Box.SevenZipSharp -OutputDirectory "${{ env.targetDirectory }}"
        shell: bash

      - name: Organising dll files
        if: steps.check.outputs.update_needed == 'true'
        run: |
          for dir in "${{ env.targetDirectory }}"/*; do
            for libDir in "$dir"/lib/*; do
              if [[ "$(basename "$libDir")" == "${{ env.framework }}" ]]; then
                cp "$libDir"/*.dll "$dir/"
              fi
            done
            for file in "$dir"/*; do
              if [[ ! "$file" =~ \.dll$ ]] && [[ ! "$file" =~ ^[lL]icence$ && "$file" != "LICENCE" ]]; then
                rm -rf "$file"
              fi
            done
            if [[ -f "$dir/.signature.p7s" ]]; then
              rm -f "$dir/.signature.p7s"
            fi
          done
        shell: bash

      - name: Create Pull Request
        if: steps.check.outputs.update_needed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'Update Nuget Packages'
          delete-branch: true
          base: main
          title: 'Update Nuget Packages'
          body: 'This PR updates Nuget Packages to the latest version.\n- PuppeteerSharp: ${{ env.PuppeteerSharp_current_version }} -> ${{ env.PuppeteerSharp_latest_version }}\n- Squid-Box.SevenZipSharp: ${{ env.SevenZipSharp_current_version }} -> ${{ env.SevenZipSharp_latest_version }}'
          token: ${{ secrets.GITHUB_TOKEN }}
